export let games = [
    { name: 'Minecraft', icon: null, slug: 'minecraft' },
    { name: 'Palworld', icon: null, slug: 'palworld' },
    { name: 'Counter-Strike 2', icon: null, slug: 'counter-strike-2' },
    { name: 'Enshrouded', icon: null, slug: 'enshrouded' },
    { name: 'Among Us', icon: null, slug: 'among-us' },
    { name: 'DotA 2', icon: null, slug: 'dota-2' },
    { name: 'Unturned', icon: null, slug: 'unturned' },
    { name: 'DayZ', icon: null, slug: 'dayz' },
    { name: 'Terraria', icon: null, slug: 'terraria' },
    { name: 'Rust', icon: null, slug: 'rust' },
    { name: 'Team Fortress 2', icon: null, slug: 'team-fortress-2' },
    { name: 'Garry’s Mod', icon: null, slug: 'garrys-mod' },
    { name: 'ARK Survival Evolved', icon: null, slug: 'ark-survival-evolved' },
    { name: 'Don’t Starve Together', icon: null, slug: 'dont-starve-together' },
    { name: 'Valheim', icon: null, slug: 'valheim' },
    { name: 'Project Zomboid', icon: null, slug: 'project-zomboid' },
    { name: '7 Days to Die', icon: null, slug: '7-days-to-die' },
    { name: 'Left 4 Dead 2', icon: null, slug: 'left-4-dead-2' },
    { name: 'Factorio', icon: null, slug: 'factorio' },
    { name: 'Risk of Rain 2', icon: null, slug: 'risk-of-rain-2' },
    { name: 'Squad', icon: null, slug: 'squad' },
    { name: 'Conan Exiles', icon: null, slug: 'conan-exiles' },
];
